const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Behaviors.Rotate,
		C3.Behaviors.Timer,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.PlayAtObject,
		C3.Plugins.Sprite.Cnds.OnCreated
	];
};
self.C3_JsPropNameTable = [
	{Plateforme: 0},
	{DéfilerVers: 0},
	{Joueur: 0},
	{Solide: 0},
	{Sol_classique: 0},
	{Plaque: 0},
	{Sinus: 0},
	{Lumière_joueur: 0},
	{Lumière_plaque: 0},
	{Lumière_clé: 0},
	{Bouton: 0},
	{Texte: 0},
	{Fond_Game_Over: 0},
	{Death: 0},
	{cle: 0},
	{dirt: 0},
	{Sol_piege: 0},
	{Cheat_admin: 0},
	{N1: 0},
	{N2: 0},
	{N3: 0},
	{N4: 0},
	{Mur_bois: 0},
	{Pokeball: 0},
	{mur_undertale: 0},
	{MurPokémon: 0},
	{Clavier: 0},
	{Ronflex: 0},
	{Death_poke: 0},
	{PlaqueVision: 0},
	{tp_poke: 0},
	{Respawn_poke: 0},
	{Etoile1: 0},
	{Undertale4: 0},
	{Undertale1: 0},
	{Undertale2: 0},
	{Rotation: 0},
	{Undertale3: 0},
	{Undertale5: 0},
	{Etoile2: 0},
	{Etoile3: 0},
	{Death_Undertale: 0},
	{Undertale: 0},
	{Death_kaizo: 0},
	{Mur_invi: 0},
	{Menu: 0},
	{Fond_dofus: 0},
	{Dofus1: 0},
	{Dofus: 0},
	{Dofus2: 0},
	{Bouftou: 0},
	{Piques: 0},
	{FakeBouftou: 0},
	{Pancarte: 0},
	{Death_Dofus: 0},
	{Dofus4: 0},
	{Kaizo: 0},
	{Logo_Dofus: 0},
	{herbe: 0},
	{pique2: 0},
	{cle2: 0},
	{Death_n23: 0},
	{ArrièreplanRépété: 0},
	{Sprite: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{ArrièreplanRépété3: 0},
	{InteractionDash: 0},
	{Minuteur: 0},
	{TextDash: 0},
	{Sprite7: 0},
	{LabsBG: 0},
	{LabsTile: 0},
	{Portal: 0},
	{Cube: 0},
	{Whisley: 0},
	{PortalGun: 0},
	{Glad0s: 0},
	{Tourelle: 0},
	{Audio: 0},
	{Icone_portal: 0},
	{Projectile: 0},
	{Joueur2: 0},
	{Death_portal: 0},
	{Death2: 0},
	{Death3: 0},
	{Death4: 0},
	{Death_n21: 0},
	{Death_n22: 0},
	{Death_n24: 0},
	{Texte2: 0},
	{Texte3: 0},
	{Poke_restant: 0},
	{DashActive: 0},
	{Dash: 0},
	{TeleportFrom: 0},
	{Collide: 0},
	{DashActive2: 0},
	{Dash2: 0}
];

self.InstanceType = {
	Joueur: class extends self.ISpriteInstance {},
	Sol_classique: class extends self.ITiledBackgroundInstance {},
	Plaque: class extends self.ISpriteInstance {},
	Lumière_joueur: class extends self.ISpriteInstance {},
	Lumière_plaque: class extends self.ISpriteInstance {},
	Lumière_clé: class extends self.ISpriteInstance {},
	Bouton: class extends self.IButtonInstance {},
	Texte: class extends self.ITextInstance {},
	Fond_Game_Over: class extends self.ITiledBackgroundInstance {},
	Death: class extends self.ISpriteInstance {},
	cle: class extends self.ISpriteInstance {},
	dirt: class extends self.ITiledBackgroundInstance {},
	Sol_piege: class extends self.ITiledBackgroundInstance {},
	Cheat_admin: class extends self.ISpriteInstance {},
	N1: class extends self.ISpriteInstance {},
	N2: class extends self.ISpriteInstance {},
	N3: class extends self.ISpriteInstance {},
	N4: class extends self.ISpriteInstance {},
	Mur_bois: class extends self.ITiledBackgroundInstance {},
	Pokeball: class extends self.ISpriteInstance {},
	mur_undertale: class extends self.ITiledBackgroundInstance {},
	MurPokémon: class extends self.ITiledBackgroundInstance {},
	Clavier: class extends self.IInstance {},
	Ronflex: class extends self.ITiledBackgroundInstance {},
	Death_poke: class extends self.ISpriteInstance {},
	PlaqueVision: class extends self.ISpriteInstance {},
	tp_poke: class extends self.ITiledBackgroundInstance {},
	Respawn_poke: class extends self.ITiledBackgroundInstance {},
	Etoile1: class extends self.ISpriteInstance {},
	Undertale4: class extends self.ISpriteInstance {},
	Undertale1: class extends self.ISpriteInstance {},
	Undertale2: class extends self.ISpriteInstance {},
	Undertale3: class extends self.ISpriteInstance {},
	Undertale5: class extends self.ISpriteInstance {},
	Etoile2: class extends self.ISpriteInstance {},
	Etoile3: class extends self.ISpriteInstance {},
	Death_Undertale: class extends self.ISpriteInstance {},
	Undertale: class extends self.ISpriteInstance {},
	Death_kaizo: class extends self.ISpriteInstance {},
	Mur_invi: class extends self.ITiledBackgroundInstance {},
	Menu: class extends self.ISpriteInstance {},
	Fond_dofus: class extends self.ITiledBackgroundInstance {},
	Dofus1: class extends self.ISpriteInstance {},
	Dofus: class extends self.ISpriteInstance {},
	Dofus2: class extends self.ISpriteInstance {},
	Bouftou: class extends self.ITiledBackgroundInstance {},
	Piques: class extends self.ITiledBackgroundInstance {},
	FakeBouftou: class extends self.ITiledBackgroundInstance {},
	Pancarte: class extends self.ITiledBackgroundInstance {},
	Death_Dofus: class extends self.ISpriteInstance {},
	Dofus4: class extends self.ISpriteInstance {},
	Kaizo: class extends self.ISpriteInstance {},
	Logo_Dofus: class extends self.ISpriteInstance {},
	herbe: class extends self.ITiledBackgroundInstance {},
	pique2: class extends self.ISpriteInstance {},
	cle2: class extends self.ISpriteInstance {},
	Death_n23: class extends self.ISpriteInstance {},
	ArrièreplanRépété: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	ArrièreplanRépété3: class extends self.ITiledBackgroundInstance {},
	InteractionDash: class extends self.ISpriteInstance {},
	TextDash: class extends self.ITextInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	LabsBG: class extends self.ITiledBackgroundInstance {},
	LabsTile: class extends self.ITiledBackgroundInstance {},
	Portal: class extends self.ISpriteInstance {},
	Cube: class extends self.ISpriteInstance {},
	Whisley: class extends self.ISpriteInstance {},
	PortalGun: class extends self.ISpriteInstance {},
	Glad0s: class extends self.ISpriteInstance {},
	Tourelle: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Icone_portal: class extends self.ISpriteInstance {},
	Joueur2: class extends self.ISpriteInstance {},
	Death_portal: class extends self.ISpriteInstance {},
	Death2: class extends self.ISpriteInstance {},
	Death3: class extends self.ISpriteInstance {},
	Death4: class extends self.ISpriteInstance {},
	Death_n21: class extends self.ISpriteInstance {},
	Death_n22: class extends self.ISpriteInstance {},
	Death_n24: class extends self.ISpriteInstance {},
	Texte2: class extends self.ITextInstance {},
	Texte3: class extends self.ITextInstance {}
}